/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MockEnsRegistryInterface extends ethers.utils.Interface {
  functions: {
    "resolver(bytes32)": FunctionFragment;
    "setResolver(bytes32,address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "resolver", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setResolver",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "resolver", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setResolver",
    data: BytesLike
  ): Result;

  events: {};
}

export class MockEnsRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MockEnsRegistryInterface;

  functions: {
    resolver(
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "resolver(bytes32)"(
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    setResolver(
      node: BytesLike,
      resolverAddr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setResolver(bytes32,address)"(
      node: BytesLike,
      resolverAddr: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  resolver(node: BytesLike, overrides?: CallOverrides): Promise<string>;

  "resolver(bytes32)"(
    node: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  setResolver(
    node: BytesLike,
    resolverAddr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setResolver(bytes32,address)"(
    node: BytesLike,
    resolverAddr: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    resolver(node: BytesLike, overrides?: CallOverrides): Promise<string>;

    "resolver(bytes32)"(
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    setResolver(
      node: BytesLike,
      resolverAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setResolver(bytes32,address)"(
      node: BytesLike,
      resolverAddr: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    resolver(node: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "resolver(bytes32)"(
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setResolver(
      node: BytesLike,
      resolverAddr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setResolver(bytes32,address)"(
      node: BytesLike,
      resolverAddr: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    resolver(
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "resolver(bytes32)"(
      node: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setResolver(
      node: BytesLike,
      resolverAddr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setResolver(bytes32,address)"(
      node: BytesLike,
      resolverAddr: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
