/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface RANKInterface extends ethers.utils.Interface {
  functions: {
    "updateBranchPrefix(address,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "updateBranchPrefix",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "updateBranchPrefix",
    data: BytesLike
  ): Result;

  events: {};
}

export class RANK extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: RANKInterface;

  functions: {
    updateBranchPrefix(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "updateBranchPrefix(address,string)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  updateBranchPrefix(
    arg0: string,
    arg1: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "updateBranchPrefix(address,string)"(
    arg0: string,
    arg1: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    updateBranchPrefix(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "updateBranchPrefix(address,string)"(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    updateBranchPrefix(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "updateBranchPrefix(address,string)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    updateBranchPrefix(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "updateBranchPrefix(address,string)"(
      arg0: string,
      arg1: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
